name: permission_plus
description: "A Flutter plugin for requesting and checking permissions."

version: 0.0.1

homepage: https://github.com/jagadeeshchoudhary/permission_plus
repository: https://github.com/jagadeeshchoudhary/permission_plus/tree/main
issue_tracker: https://github.com/jagadeeshchoudhary/permission_plus/issues

environment:
  sdk: ^3.12.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  permission_plus_platform_interface: ^0.0.1
  permission_plus_web: ^0.0.1
  permission_plus_windows: ^0.0.1
  permission_plus_linux: ^0.0.1
  permission_plus_apple: ^0.0.1
  permission_plus_android: ^0.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_plus_android
      web:
        default_package: permission_plus_web
      windows:
        default_package: permission_plus_windows
      linux:
        default_package: permission_plus_linux
      macos:
        default_package: permission_plus_apple
      ios:
        default_package: permission_plus_apple

topics:
  - permissions